wandb_version: 1

model_learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: GCN
dataset:
  desc: null
  value: PubMed
epochs:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706788299.253543
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 77
      2:
      - 1
      - 11
      - 49
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.16.0
      6: 4.36.2
      8:
      - 5
      13: darwin-x86_64
